services:
  hr-app:
    build:
      context: .
      args:
        TOKEN_SECRET: ${TOKEN_SECRET:-}
    image: scos-hr:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data

volumes: {}